debunker:
  token: "<token>"
  target: 1234567890
  username: anxiety_debunker_bot
  intro: "Hi!!"

repo:
  inmemory: false
  datasource:
    url: jdbc:postgresql://<host>/<schema>
    password: <password>
    user: <user>